apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-config
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-backend
    kind: SecretStore
  target:
    name: app-config
  data:
    - secretKey: api_key
      remoteRef:
        key: prod/app-config
        property: api_key
    - secretKey: db_url
      remoteRef:
        key: prod/app-config
        property: db_url
    - secretKey: cache_url
      remoteRef:
        key: prod/app-config
        property: cache_url