apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appConfig.secretName }}
  namespace: {{ .Values.global.environment }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.appConfig.secretName }}
  data:
    {{- range .Values.appConfig.keys }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ if eq $.Values.global.environment "prod" }}{{ $.Values.appConfig.secretPath.prod }}{{ else }}{{ $.Values.appConfig.secretPath.dev }}{{ end }}
        property: {{ .name }}
    {{- end }}
