apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-test-app
  namespace: {{ .Values.global.environment }}
  labels:
    app: test-app
    environment: {{ .Values.global.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: test-app
        environment: {{ .Values.global.environment }}
    spec:
      containers:
      - name: test-app
        image: nginx
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appConfig.secretName }}
              key: api_key
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appConfig.secretName }}
              key: db_url
        - name: CACHE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appConfig.secretName }}
              key: cache_url
